export const doublelist = [
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder 1",
        'id': "1",
        'parents': ['1QLSNL1QhMMHJmDVFyTXoQ2V6RBtc8mjx'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder 2",
        'id': "2",
        'parents': ['1'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder 3",
        'id': "3",
        'parents': ['2'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "!Folder 4",
        'id': "4",
        'parents': ['3'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder 5",
        'id': "5",
        'parents': ['4'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder 6",
        'id': "6",
        'parents': ['5'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "!Folder 7",
        'id': "7",
        'parents': ['6'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder 8",
        'id': "8",
        'parents': ['7'],
    },
    {
        'mimeType': "/google-apps.document",
        'name': "Document 1",
        'id': "9",
        'parents': ['8'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder A",
        'id': "10",
        'parents': ['1QLSNL1QhMMHJmDVFyTXoQ2V6RBtc8mjx'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder B",
        'id': "11",
        'parents': ['10'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder C",
        'id': "12",
        'parents': ['11'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder D",
        'id': "13",
        'parents': ['12'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder E",
        'id': "14",
        'parents': ['13'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder F",
        'id': "15",
        'parents': ['14'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "!Folder G",
        'id': "16",
        'parents': ['15'],
    },
    {
        'mimeType': "/google-apps.folder",
        'name': "Folder H",
        'id': "17",
        'parents': ['16'],
    },
    {
        'mimeType': "/google-apps.document",
        'name': "Document A",
        'id': "18",
        'parents': ['17'],
    },
    
];